project_id = "oyrwvxztgqvjrkkkxrjo"

[functions.import-emails]
verify_jwt = false

[functions.send-email-reply]
verify_jwt = true

[functions.analyze-image]
verify_jwt = false

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.imap-connect]
verify_jwt = true

[functions.imap-import]
verify_jwt = true

[functions.imap-send]
verify_jwt = true

